# Generated by Django 4.1.7 on 2023-03-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(help_text='Только латинские буквы, цифры, знаки "_" и "-".', unique=True, verbose_name='Название меню')),
                ('structure', models.JSONField(blank=True, null=True, verbose_name='Структура меню')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню',
                'ordering': ['title'],
            },
        ),
    ]
